### YamlMime:ManagedReference
items:
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
  commentId: T:Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
  id: JsonConfigBuilder
  parent: Sparkle.CSharp.IO.Configs.Json
  children:
  - Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.#ctor(System.String,System.String,System.String)
  - Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add``1(System.String,``0)
  - Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Build
  langs:
  - csharp
  - vb
  name: JsonConfigBuilder
  nameWithType: JsonConfigBuilder
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
  type: Class
  source:
    remote:
      path: src/Sparkle/CSharp/IO/Configs/Json/JsonConfigBuilder.cs
      branch: main
      repo: https://github.com/MrScautHD/Sparkle.git
    id: JsonConfigBuilder
    path: ../src/Sparkle/CSharp/IO/Configs/Json/JsonConfigBuilder.cs
    startLine: 2
  assemblies:
  - Sparkle
  namespace: Sparkle.CSharp.IO.Configs.Json
  syntax:
    content: public class JsonConfigBuilder
    content.vb: Public Class JsonConfigBuilder
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.#ctor(System.String,System.String,System.String)
  commentId: M:Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
  langs:
  - csharp
  - vb
  name: JsonConfigBuilder(string, string, string)
  nameWithType: JsonConfigBuilder.JsonConfigBuilder(string, string, string)
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.JsonConfigBuilder(string, string, string)
  type: Constructor
  source:
    remote:
      path: src/Sparkle/CSharp/IO/Configs/Json/JsonConfigBuilder.cs
      branch: main
      repo: https://github.com/MrScautHD/Sparkle.git
    id: .ctor
    path: ../src/Sparkle/CSharp/IO/Configs/Json/JsonConfigBuilder.cs
    startLine: 27
  assemblies:
  - Sparkle
  namespace: Sparkle.CSharp.IO.Configs.Json
  summary: Represents a builder for creating JSON configurations.
  example: []
  syntax:
    content: public JsonConfigBuilder(string directory, string name, string encryptKey = "")
    parameters:
    - id: directory
      type: System.String
    - id: name
      type: System.String
    - id: encryptKey
      type: System.String
    content.vb: Public Sub New(directory As String, name As String, encryptKey As String = "")
  overload: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.#ctor*
  nameWithType.vb: JsonConfigBuilder.New(String, String, String)
  fullName.vb: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.New(String, String, String)
  name.vb: New(String, String, String)
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add``1(System.String,``0)
  commentId: M:Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add``1(System.String,``0)
  id: Add``1(System.String,``0)
  parent: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
  langs:
  - csharp
  - vb
  name: Add<T>(string, T)
  nameWithType: JsonConfigBuilder.Add<T>(string, T)
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add<T>(string, T)
  type: Method
  source:
    remote:
      path: src/Sparkle/CSharp/IO/Configs/Json/JsonConfigBuilder.cs
      branch: main
      repo: https://github.com/MrScautHD/Sparkle.git
    id: Add
    path: ../src/Sparkle/CSharp/IO/Configs/Json/JsonConfigBuilder.cs
    startLine: 41
  assemblies:
  - Sparkle
  namespace: Sparkle.CSharp.IO.Configs.Json
  summary: Adds a key-value pair to the JSON configuration builder.
  example: []
  syntax:
    content: public JsonConfigBuilder Add<T>(string key, T value)
    parameters:
    - id: key
      type: System.String
      description: The key of the value.
    - id: value
      type: '{T}'
      description: The value to be added.
    typeParameters:
    - id: T
      description: The type of the value.
    return:
      type: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
      description: The updated JSON configuration builder.
    content.vb: Public Function Add(Of T)(key As String, value As T) As JsonConfigBuilder
  overload: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add*
  nameWithType.vb: JsonConfigBuilder.Add(Of T)(String, T)
  fullName.vb: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add(Of T)(String, T)
  name.vb: Add(Of T)(String, T)
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Build
  commentId: M:Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Build
  id: Build
  parent: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
  langs:
  - csharp
  - vb
  name: Build()
  nameWithType: JsonConfigBuilder.Build()
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Build()
  type: Method
  source:
    remote:
      path: src/Sparkle/CSharp/IO/Configs/Json/JsonConfigBuilder.cs
      branch: main
      repo: https://github.com/MrScautHD/Sparkle.git
    id: Build
    path: ../src/Sparkle/CSharp/IO/Configs/Json/JsonConfigBuilder.cs
    startLine: 50
  assemblies:
  - Sparkle
  namespace: Sparkle.CSharp.IO.Configs.Json
  summary: Builds a JSON configuration file using the values added to the builder.
  example: []
  syntax:
    content: public JsonConfig Build()
    return:
      type: Sparkle.CSharp.IO.Configs.Json.JsonConfig
      description: The created JSON configuration file.
    content.vb: Public Function Build() As JsonConfig
  overload: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Build*
references:
- uid: Sparkle.CSharp.IO.Configs.Json
  commentId: N:Sparkle.CSharp.IO.Configs.Json
  href: Sparkle.html
  name: Sparkle.CSharp.IO.Configs.Json
  nameWithType: Sparkle.CSharp.IO.Configs.Json
  fullName: Sparkle.CSharp.IO.Configs.Json
  spec.csharp:
  - uid: Sparkle
    name: Sparkle
    href: Sparkle.html
  - name: .
  - uid: Sparkle.CSharp
    name: CSharp
    href: Sparkle.CSharp.html
  - name: .
  - uid: Sparkle.CSharp.IO
    name: IO
    href: Sparkle.CSharp.IO.html
  - name: .
  - uid: Sparkle.CSharp.IO.Configs
    name: Configs
    href: Sparkle.CSharp.IO.Configs.html
  - name: .
  - uid: Sparkle.CSharp.IO.Configs.Json
    name: Json
    href: Sparkle.CSharp.IO.Configs.Json.html
  spec.vb:
  - uid: Sparkle
    name: Sparkle
    href: Sparkle.html
  - name: .
  - uid: Sparkle.CSharp
    name: CSharp
    href: Sparkle.CSharp.html
  - name: .
  - uid: Sparkle.CSharp.IO
    name: IO
    href: Sparkle.CSharp.IO.html
  - name: .
  - uid: Sparkle.CSharp.IO.Configs
    name: Configs
    href: Sparkle.CSharp.IO.Configs.html
  - name: .
  - uid: Sparkle.CSharp.IO.Configs.Json
    name: Json
    href: Sparkle.CSharp.IO.Configs.Json.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.#ctor*
  commentId: Overload:Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.#ctor
  href: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.html#Sparkle_CSharp_IO_Configs_Json_JsonConfigBuilder__ctor_System_String_System_String_System_String_
  name: JsonConfigBuilder
  nameWithType: JsonConfigBuilder.JsonConfigBuilder
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.JsonConfigBuilder
  nameWithType.vb: JsonConfigBuilder.New
  fullName.vb: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.New
  name.vb: New
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add*
  commentId: Overload:Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add
  href: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.html#Sparkle_CSharp_IO_Configs_Json_JsonConfigBuilder_Add__1_System_String___0_
  name: Add
  nameWithType: JsonConfigBuilder.Add
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Add
- uid: '{T}'
  commentId: '!:T'
  definition: T
  name: T
  nameWithType: T
  fullName: T
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
  commentId: T:Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
  parent: Sparkle.CSharp.IO.Configs.Json
  href: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.html
  name: JsonConfigBuilder
  nameWithType: JsonConfigBuilder
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder
- uid: T
  name: T
  nameWithType: T
  fullName: T
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Build*
  commentId: Overload:Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Build
  href: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.html#Sparkle_CSharp_IO_Configs_Json_JsonConfigBuilder_Build
  name: Build
  nameWithType: JsonConfigBuilder.Build
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfigBuilder.Build
- uid: Sparkle.CSharp.IO.Configs.Json.JsonConfig
  commentId: T:Sparkle.CSharp.IO.Configs.Json.JsonConfig
  parent: Sparkle.CSharp.IO.Configs.Json
  href: Sparkle.CSharp.IO.Configs.Json.JsonConfig.html
  name: JsonConfig
  nameWithType: JsonConfig
  fullName: Sparkle.CSharp.IO.Configs.Json.JsonConfig
