### YamlMime:ManagedReference
items:
- uid: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D
  commentId: T:Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D
  id: PhysicsSettings3D
  parent: Sparkle.CSharp.Physics.Dim3
  children:
  - Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.#ctor
  - Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.Gravity
  - Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.MultiThreaded
  langs:
  - csharp
  - vb
  name: PhysicsSettings3D
  nameWithType: PhysicsSettings3D
  fullName: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D
  type: Struct
  source:
    remote:
      path: src/Sparkle/CSharp/Physics/Dim3/PhysicsSettings3D.cs
      branch: main
      repo: https://github.com/MrScautHD/Sparkle.git
    id: PhysicsSettings3D
    path: ../src/Sparkle/CSharp/Physics/Dim3/PhysicsSettings3D.cs
    startLine: 4
  assemblies:
  - Sparkle
  namespace: Sparkle.CSharp.Physics.Dim3
  syntax:
    content: public struct PhysicsSettings3D
    content.vb: Public Structure PhysicsSettings3D
  inheritedMembers:
  - System.ValueType.Equals(System.Object)
  - System.ValueType.GetHashCode
  - System.ValueType.ToString
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.ReferenceEquals(System.Object,System.Object)
- uid: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.Gravity
  commentId: F:Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.Gravity
  id: Gravity
  parent: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D
  langs:
  - csharp
  - vb
  name: Gravity
  nameWithType: PhysicsSettings3D.Gravity
  fullName: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.Gravity
  type: Field
  source:
    remote:
      path: src/Sparkle/CSharp/Physics/Dim3/PhysicsSettings3D.cs
      branch: main
      repo: https://github.com/MrScautHD/Sparkle.git
    id: Gravity
    path: ../src/Sparkle/CSharp/Physics/Dim3/PhysicsSettings3D.cs
    startLine: 10
  assemblies:
  - Sparkle
  namespace: Sparkle.CSharp.Physics.Dim3
  summary: >-
    The gravitational force applied in the simulation.

    Default is (0, -9.81, 0) representing Earth's gravity.
  example: []
  syntax:
    content: public Vector3 Gravity
    return:
      type: System.Numerics.Vector3
    content.vb: Public Gravity As Vector3
- uid: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.MultiThreaded
  commentId: F:Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.MultiThreaded
  id: MultiThreaded
  parent: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D
  langs:
  - csharp
  - vb
  name: MultiThreaded
  nameWithType: PhysicsSettings3D.MultiThreaded
  fullName: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.MultiThreaded
  type: Field
  source:
    remote:
      path: src/Sparkle/CSharp/Physics/Dim3/PhysicsSettings3D.cs
      branch: main
      repo: https://github.com/MrScautHD/Sparkle.git
    id: MultiThreaded
    path: ../src/Sparkle/CSharp/Physics/Dim3/PhysicsSettings3D.cs
    startLine: 15
  assemblies:
  - Sparkle
  namespace: Sparkle.CSharp.Physics.Dim3
  summary: Specifies whether the physics simulation runs using multiple threads.
  example: []
  syntax:
    content: public bool MultiThreaded
    return:
      type: System.Boolean
    content.vb: Public MultiThreaded As Boolean
- uid: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.#ctor
  commentId: M:Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.#ctor
  id: '#ctor'
  parent: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D
  langs:
  - csharp
  - vb
  name: PhysicsSettings3D()
  nameWithType: PhysicsSettings3D.PhysicsSettings3D()
  fullName: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.PhysicsSettings3D()
  type: Constructor
  source:
    remote:
      path: src/Sparkle/CSharp/Physics/Dim3/PhysicsSettings3D.cs
      branch: main
      repo: https://github.com/MrScautHD/Sparkle.git
    id: .ctor
    path: ../src/Sparkle/CSharp/Physics/Dim3/PhysicsSettings3D.cs
    startLine: 20
  assemblies:
  - Sparkle
  namespace: Sparkle.CSharp.Physics.Dim3
  summary: Represents the settings for the physics engine.
  example: []
  syntax:
    content: public PhysicsSettings3D()
    content.vb: Public Sub New()
  overload: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.#ctor*
  nameWithType.vb: PhysicsSettings3D.New()
  fullName.vb: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.New()
  name.vb: New()
references:
- uid: Sparkle.CSharp.Physics.Dim3
  commentId: N:Sparkle.CSharp.Physics.Dim3
  href: Sparkle.html
  name: Sparkle.CSharp.Physics.Dim3
  nameWithType: Sparkle.CSharp.Physics.Dim3
  fullName: Sparkle.CSharp.Physics.Dim3
  spec.csharp:
  - uid: Sparkle
    name: Sparkle
    href: Sparkle.html
  - name: .
  - uid: Sparkle.CSharp
    name: CSharp
    href: Sparkle.CSharp.html
  - name: .
  - uid: Sparkle.CSharp.Physics
    name: Physics
    href: Sparkle.CSharp.Physics.html
  - name: .
  - uid: Sparkle.CSharp.Physics.Dim3
    name: Dim3
    href: Sparkle.CSharp.Physics.Dim3.html
  spec.vb:
  - uid: Sparkle
    name: Sparkle
    href: Sparkle.html
  - name: .
  - uid: Sparkle.CSharp
    name: CSharp
    href: Sparkle.CSharp.html
  - name: .
  - uid: Sparkle.CSharp.Physics
    name: Physics
    href: Sparkle.CSharp.Physics.html
  - name: .
  - uid: Sparkle.CSharp.Physics.Dim3
    name: Dim3
    href: Sparkle.CSharp.Physics.Dim3.html
- uid: System.ValueType.Equals(System.Object)
  commentId: M:System.ValueType.Equals(System.Object)
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  name: Equals(object)
  nameWithType: ValueType.Equals(object)
  fullName: System.ValueType.Equals(object)
  nameWithType.vb: ValueType.Equals(Object)
  fullName.vb: System.ValueType.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.ValueType.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.equals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType.GetHashCode
  commentId: M:System.ValueType.GetHashCode
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  name: GetHashCode()
  nameWithType: ValueType.GetHashCode()
  fullName: System.ValueType.GetHashCode()
  spec.csharp:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.gethashcode
  - name: (
  - name: )
- uid: System.ValueType.ToString
  commentId: M:System.ValueType.ToString
  parent: System.ValueType
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  name: ToString()
  nameWithType: ValueType.ToString()
  fullName: System.ValueType.ToString()
  spec.csharp:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.ValueType.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.valuetype.tostring
  - name: (
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.ValueType
  commentId: T:System.ValueType
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.valuetype
  name: ValueType
  nameWithType: ValueType
  fullName: System.ValueType
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Numerics.Vector3
  commentId: T:System.Numerics.Vector3
  parent: System.Numerics
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.numerics.vector3
  name: Vector3
  nameWithType: Vector3
  fullName: System.Numerics.Vector3
- uid: System.Numerics
  commentId: N:System.Numerics
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Numerics
  nameWithType: System.Numerics
  fullName: System.Numerics
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Numerics
    name: Numerics
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.numerics
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Numerics
    name: Numerics
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.numerics
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.#ctor*
  commentId: Overload:Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.#ctor
  href: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.html#Sparkle_CSharp_Physics_Dim3_PhysicsSettings3D__ctor
  name: PhysicsSettings3D
  nameWithType: PhysicsSettings3D.PhysicsSettings3D
  fullName: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.PhysicsSettings3D
  nameWithType.vb: PhysicsSettings3D.New
  fullName.vb: Sparkle.CSharp.Physics.Dim3.PhysicsSettings3D.New
  name.vb: New
